eval $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)
export SSH_AUTH_SOCK

# https://bbs.archlinux.org/viewtopic.php?id=224787
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY
# systemctl --user mask xdg-desktop-portal-gnome

mkdir -p $XDG_RUNTIME_DIR/gvfsd-sftp

xautolock -time 10 -locker slock &
skippy-xd --start-daemon &

#exec gnome-session
exec openbox-session
