# -*- mode: shell-script; -*-
[[ $TERM == "dumb" ]] && unsetopt zle && PS1='$ ' && return

export ADOTDIR=~/.config/zsh/antigen-repo

source ~/.config/zsh/antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle svn
antigen bundle virtualenv
antigen bundle pip

# Syntax highlighting bundle.
antigen bundle zdharma-continuum/fast-syntax-highlighting

# Highlight history search bundle.
antigen bundle zsh-users/zsh-history-substring-search

# Zsh autosuggestions
antigen bundle zsh-users/zsh-autosuggestions

# Zsh completion.
antigen bundle zsh-users/zsh-completions

# pkgtools library
antigen bundle xgarrido/zsh-pkgtools

# Homemade utilities
antigen bundle xgarrido/zsh-utilities

# Package manager
antigen bundle xgarrido/zsh-pkgman

# dotfiles manager
antigen bundle xgarrido/zsh-dotfiles

# Org-pages generation
antigen bundle xgarrido/zsh-org-pages

# Load the theme.
antigen bundle xgarrido/zsh-themes
antigen theme xgarrido/zsh-themes nemo

# Tell antigen that you're done.
antigen apply
